config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/admin', to: 'admins#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  resources :microposts
  resources :users
  namespace :admin do
    resources :foods
    resources :users
  end
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/food.rb
class Food < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  has_many :comments
  has_many :food_restaurants
  has_many :restaurants, through: :food_restaurant
  has_one_attached :image

  scope :search, ->(name){where "name LIKE ?", "%#{name}%"}

end

app/controllers/admin/foods_controller.rb
class Admin::FoodsController < Admin::BaseController
  before_action :food_params, only: [:create]
  before_action :find_food, only: [:show, :edit, :update]
  
  def index
    @foods = Food.search(params[:search])
    @foods = @foods.page(params[:page]).per(5)
    # @foods = @foods.search(params[:search])
  end

  def show; end
  
  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    @food.image.attach(params[:food][:image])
    if @food.save
      flash[:success] = "Food created!"
      redirect_to admin_foods_path
    else
      flash[:danger] = "Food no created!"
      render :new
    end
  end

  def edit; end

  def update
    if @food.update(food_params)
      flash[:success] = "food updated"
      redirect_to admin_foods_path
    # Handle a successful update.
    else
      render :edit
    end
  end

  def destroy
    Food.find(params[:id]).destroy
    flash[:success] = "Food deleted"
    redirect_to admin_foods_path
  end

  private

  def find_food
    @food = Food.find_by(id: params[:id])
  end

  def food_params
    params.require(:food).permit(:name, :food_content, :image, :category_id)
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

end

app/views/admin/foods/_food.html.erb
<li id="food-<%= food.id %>">
	<span class="user"><%= link_to food.user.name, food.user %></span>
	<span class="content">
		<%= food.food_content %>
		<%= image_tag food.image if food.image.attached? %>
	</span>
	<span class="timestamp">
		Posted <%= time_ago_in_words(food.created_at) %> ago.
		<% if current_user?(food.user) %>
		<%= link_to "delete", food, method: :delete,
		data: { confirm: "You sure?" } %>
		<% end %>
	</span>
</li>

app/views/admin/foods/edit.html.erb
<% provide(:title, 'edit food') %>
<h1>edit food</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @food] do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.label :food_content %>
      <%= f.text_field :food_content, class: 'form-control' %>
      <%= f.select :category_id, options_for_select(Category.all.map { |category| [category.name, category.id] }) %>
      <span class="image">
        <%= f.file_field :image %>
      </span>
      <%= f.submit "submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/foods/index.html.erb
<% provide(:title, 'All food') %>
  <%= form_tag admin_foods_path, method: :get  do %>
    <%= text_field_tag :search, params[:search]%>
    <%= submit_tag "Search", :name => nil%>
  <% end %>
  <div>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= food.food_content %></td>
        <td><%= image_tag food.image if food.image.attached?%></td>
        <td><%= link_to 'Show', admin_food_path(food) %></td>
        <td><%= link_to 'Edit', edit_admin_food_path(food) %></td>
        <%= link_to "delete", admin_food_path(food), method: :delete, data: { confirm: "You sure?" } %>
      </tr>
      <br>
    <% end %>
  </div>
<%= paginate @foods %>

app/views/admin/foods/new.html.erb
<% provide(:title, 'create food') %>
<h1>Create food</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @food] do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.label :food_content %>
      <%= f.text_field :food_content, class: 'form-control' %>
      <%= f.select :category_id, options_for_select(Category.all.map { |category| [category.name, category.id] }) %>
      <span class="image">
        <%= f.file_field :image %>
      </span>
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/foods/show.html.erb
<% provide(:title, @food) %>
<div class="row">
	<aside class="col-md-4">
	<h1>
		<td><%= @food.name %></td>
    <td><%= @food.food_content %></td>
    <td><%= image_tag @food.image if @food.image.attached?%></td>
	</h1>
	</aside>
</div>