config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/admin', to: 'admins#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  resources :microposts
  resources :users
  namespace :admin do
    resources :foods
    resources :users
  end
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :content, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true
  has_one_attached :image
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :find_micropost, only: [:edit, :update]
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,only: :destroy

  def index
    @microposts = Micropost.all
  end

  def create
    @micropost = current_user.microposts.build(micropost_params)
    @micropost.image.attach(params[:micropost][:image])
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to user_path(current_user)
    else
      @feed_items = current_user.feed.page(params[:page])
      flash[:danger] = "Micropost create fail"
      redirect_to root_path
    end
  end

  def edit
    unless @micropost.user.id == current_user.id
      flash[:danger] = "You do not have access"
      redirect_to root_path
    end
  end

  def update
    if @micropost.update(micropost_params)
      flash[:success] = "micropost updated!"
      redirect_to user_path(current_user)
    else
      flash[:danger] = "Micropost update fail"
      render :edit
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || micropost_path
  end

  private

  def find_micropost
    @micropost = Micropost.find_by(id: params[:id])
  end

  def micropost_params
    params.require(:micropost).permit(:content, :image)
  end

  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    redirect_to root_url if @micropost.nil?
  end
end

app/views/microposts/_form.html.erb
<%#form_for mặc định chạy vào post tức là action create trong microposts%>
<%= form_for @micropost do |f| %>  
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "submit", class: "btn btn-primary" %>
<% end %>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
	<span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user?(micropost.user) %>
        <%= link_to 'Edit', edit_micropost_path(id: micropost.id, user_id: micropost.user_id)%>
        <%= link_to "delete", micropost, method: :delete, data: { confirm: "You sure?" } %>
      <% end %>
  </span>
</li>

app/views/microposts/edit.html.erb
<%= render 'form'%>

app/views/microposts/index.html.erb
<% provide(:title, 'All microposts') %>
  <% @microposts.each do |post| %>
    <tr>
      <td><%= post.content %></td>
      <td><%= link_to 'Show', post %></td>
      <td><%= link_to 'Edit', edit_micropost_path(post) %></td>
      <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    </br>
<% end %>

app/views/microposts/new.html.erb
<%= render 'form'%>

app/views/microposts/show.html.erb
<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>